# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/macbreaker/gitProjects/samples/sdl2/spriteTest

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/macbreaker/gitProjects/samples/sdl2/spriteTest

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/macbreaker/gitProjects/samples/sdl2/spriteTest/CMakeFiles /Users/macbreaker/gitProjects/samples/sdl2/spriteTest/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/macbreaker/gitProjects/samples/sdl2/spriteTest/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named spritetest.self

# Build rule for target.
spritetest.self: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spritetest.self
.PHONY : spritetest.self

# fast build rule for target.
spritetest.self/fast:
	$(MAKE) -f CMakeFiles/spritetest.self.dir/build.make CMakeFiles/spritetest.self.dir/build
.PHONY : spritetest.self/fast

#=============================================================================
# Target rules for targets named spritetest.vpk

# Build rule for target.
spritetest.vpk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spritetest.vpk
.PHONY : spritetest.vpk

# fast build rule for target.
spritetest.vpk/fast:
	$(MAKE) -f CMakeFiles/spritetest.vpk.dir/build.make CMakeFiles/spritetest.vpk.dir/build
.PHONY : spritetest.vpk/fast

#=============================================================================
# Target rules for targets named spritetest

# Build rule for target.
spritetest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spritetest
.PHONY : spritetest

# fast build rule for target.
spritetest/fast:
	$(MAKE) -f CMakeFiles/spritetest.dir/build.make CMakeFiles/spritetest.dir/build
.PHONY : spritetest/fast

src/grid.obj: src/grid.cpp.obj

.PHONY : src/grid.obj

# target to build an object file
src/grid.cpp.obj:
	$(MAKE) -f CMakeFiles/spritetest.dir/build.make CMakeFiles/spritetest.dir/src/grid.cpp.obj
.PHONY : src/grid.cpp.obj

src/grid.i: src/grid.cpp.i

.PHONY : src/grid.i

# target to preprocess a source file
src/grid.cpp.i:
	$(MAKE) -f CMakeFiles/spritetest.dir/build.make CMakeFiles/spritetest.dir/src/grid.cpp.i
.PHONY : src/grid.cpp.i

src/grid.s: src/grid.cpp.s

.PHONY : src/grid.s

# target to generate assembly for a file
src/grid.cpp.s:
	$(MAKE) -f CMakeFiles/spritetest.dir/build.make CMakeFiles/spritetest.dir/src/grid.cpp.s
.PHONY : src/grid.cpp.s

src/main.obj: src/main.cpp.obj

.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) -f CMakeFiles/spritetest.dir/build.make CMakeFiles/spritetest.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/spritetest.dir/build.make CMakeFiles/spritetest.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/spritetest.dir/build.make CMakeFiles/spritetest.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... spritetest.self"
	@echo "... spritetest.vpk"
	@echo "... spritetest"
	@echo "... src/grid.obj"
	@echo "... src/grid.i"
	@echo "... src/grid.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

